### ISSUE TITLE
broken link to installation prerequisites

### ISSUE THREAD

**Issue by bradfordbulger-nasa** [simplesamlphp/docs#11]
On the page "[Installing SimpleSAMLphp from the repository](https://simplesamlphp.org/docs/devel/simplesamlphp-install-repo.html)" there is a link to the installation prerequisites that goes to

https://simplesamlphp.org/docs/simplesamlphp-install.html

That doesn't exist. The prerequisites page from this documentation that I can find is "Prerequisites" under "SimpleSAMLphp Installation and Configuration"

https://simplesamlphp.org/docs/devel/simplesamlphp-install.html#prerequisites

This all seems to be the same for the latest stable release - /docs/2.3/ - as for the devel version.

**Comment by tvdijen** [comment]
Thanks! I fixed it
