### ISSUE TITLE
Trigger docs rebuild on main repo change

### ISSUE THREAD

**Issue by thijskh** [simplesamlphp/docs#2]
Currently the docs website is only rebuilt when something changes in _this_ repo.

However, it should be rebuilt if the source files change. Those live primarily in the simplesamlphp/simplesamlphp repo (but, to make things complicated, also sometimes in module repos).

Some possible solutions:
- Trigger this repo's workflow when a commit (including docs changes?) is done in the ssp main repo. And/or do the same from the module repos.
- Just rebuild this repo periodically (daily/weekly).

**Comment by tvdijen** [comment]
It would be great if we could trigger this from any other repo, but _only_ if any of the md-files have changed..
I think [this](https://github.com/tj-actions/changed-files) action can help us to detect that.
