### ISSUE TITLE
Missing documentation (dead links)

### ISSUE THREAD

**Issue by ziQ** [simplesamlphp/docs#7]
**Describe the bug**
The simpleSAMLphp documentation contains a lot of dead links.

**To Reproduce**
1. Go to https://simplesamlphp.org/docs/latest/simplesamlphp-idp.html
1. Click on "authcrypt:Hash" or "ldap:LDAP" or "sqlauth:SQL" or ...
1. See error 404 File not found

**Expected behavior**
Existing documentation, links not dead.

**Screenshots or logs**
![screenshot_2022-06-10_115411](https://user-images.githubusercontent.com/124074/173040716-281c635d-899a-4e98-ab42-19640d9b417f.png)

**Additional context**
Also checked `docs/` directory in Github, but the files are not present there either.

Broken/dead documentation links:
- https://simplesamlphp.org/docs/latest/authcrypt/authcrypt.html
- https://simplesamlphp.org/docs/latest/authX509/authX509.html
- https://simplesamlphp.org/docs/latest/ldap/ldap.html
- https://simplesamlphp.org/docs/latest/sqlauth/sql.html
- https://simplesamlphp.org/docs/latest/radius/radius.html
- ...

**Comment by thijskh** [comment]
Fixed these links now in the 2.0 and 1.19 docs, thanks for reporting!
